# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /bin/cmake

# The command to remove a file.
RM = /bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/noerlol/C-Projects/RocketGE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/noerlol/C-Projects/RocketGE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noerlol/C-Projects/RocketGE/CMakeFiles /home/noerlol/C-Projects/RocketGE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noerlol/C-Projects/RocketGE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RocketRuntime

# Build rule for target.
RocketRuntime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RocketRuntime
.PHONY : RocketRuntime

# fast build rule for target.
RocketRuntime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/build
.PHONY : RocketRuntime/fast

#=============================================================================
# Target rules for targets named rectangle_test

# Build rule for target.
rectangle_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rectangle_test
.PHONY : rectangle_test

# fast build rule for target.
rectangle_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/build
.PHONY : rectangle_test/fast

#=============================================================================
# Target rules for targets named initializer_test

# Build rule for target.
initializer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 initializer_test
.PHONY : initializer_test

# fast build rule for target.
initializer_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/build
.PHONY : initializer_test/fast

src/asset.o: src/asset.cpp.o
.PHONY : src/asset.o

# target to build an object file
src/asset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/asset.cpp.o
.PHONY : src/asset.cpp.o

src/asset.i: src/asset.cpp.i
.PHONY : src/asset.i

# target to preprocess a source file
src/asset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/asset.cpp.i
.PHONY : src/asset.cpp.i

src/asset.s: src/asset.cpp.s
.PHONY : src/asset.s

# target to generate assembly for a file
src/asset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/asset.cpp.s
.PHONY : src/asset.cpp.s

src/io.o: src/io.cpp.o
.PHONY : src/io.o

# target to build an object file
src/io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/io.cpp.o
.PHONY : src/io.cpp.o

src/io.i: src/io.cpp.i
.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s
.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/renderer3d.o: src/renderer3d.cpp.o
.PHONY : src/renderer3d.o

# target to build an object file
src/renderer3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/renderer3d.cpp.o
.PHONY : src/renderer3d.cpp.o

src/renderer3d.i: src/renderer3d.cpp.i
.PHONY : src/renderer3d.i

# target to preprocess a source file
src/renderer3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/renderer3d.cpp.i
.PHONY : src/renderer3d.cpp.i

src/renderer3d.s: src/renderer3d.cpp.s
.PHONY : src/renderer3d.s

# target to generate assembly for a file
src/renderer3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/renderer3d.cpp.s
.PHONY : src/renderer3d.cpp.s

src/types.o: src/types.cpp.o
.PHONY : src/types.o

# target to build an object file
src/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/types.cpp.o
.PHONY : src/types.cpp.o

src/types.i: src/types.cpp.i
.PHONY : src/types.i

# target to preprocess a source file
src/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/types.cpp.i
.PHONY : src/types.cpp.i

src/types.s: src/types.cpp.s
.PHONY : src/types.s

# target to generate assembly for a file
src/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/types.cpp.s
.PHONY : src/types.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

tests/initializer_test.o: tests/initializer_test.cpp.o
.PHONY : tests/initializer_test.o

# target to build an object file
tests/initializer_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/tests/initializer_test.cpp.o
.PHONY : tests/initializer_test.cpp.o

tests/initializer_test.i: tests/initializer_test.cpp.i
.PHONY : tests/initializer_test.i

# target to preprocess a source file
tests/initializer_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/tests/initializer_test.cpp.i
.PHONY : tests/initializer_test.cpp.i

tests/initializer_test.s: tests/initializer_test.cpp.s
.PHONY : tests/initializer_test.s

# target to generate assembly for a file
tests/initializer_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/tests/initializer_test.cpp.s
.PHONY : tests/initializer_test.cpp.s

tests/rectangle_test.o: tests/rectangle_test.cpp.o
.PHONY : tests/rectangle_test.o

# target to build an object file
tests/rectangle_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/tests/rectangle_test.cpp.o
.PHONY : tests/rectangle_test.cpp.o

tests/rectangle_test.i: tests/rectangle_test.cpp.i
.PHONY : tests/rectangle_test.i

# target to preprocess a source file
tests/rectangle_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/tests/rectangle_test.cpp.i
.PHONY : tests/rectangle_test.cpp.i

tests/rectangle_test.s: tests/rectangle_test.cpp.s
.PHONY : tests/rectangle_test.s

# target to generate assembly for a file
tests/rectangle_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/tests/rectangle_test.cpp.s
.PHONY : tests/rectangle_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RocketRuntime"
	@echo "... initializer_test"
	@echo "... rectangle_test"
	@echo "... src/asset.o"
	@echo "... src/asset.i"
	@echo "... src/asset.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/renderer3d.o"
	@echo "... src/renderer3d.i"
	@echo "... src/renderer3d.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
	@echo "... tests/initializer_test.o"
	@echo "... tests/initializer_test.i"
	@echo "... tests/initializer_test.s"
	@echo "... tests/rectangle_test.o"
	@echo "... tests/rectangle_test.i"
	@echo "... tests/rectangle_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

