# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/noerlol/C-Projects/RocketGE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/noerlol/C-Projects/RocketGE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noerlol/C-Projects/RocketGE/CMakeFiles /home/noerlol/C-Projects/RocketGE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noerlol/C-Projects/RocketGE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RocketRuntime

# Build rule for target.
RocketRuntime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RocketRuntime
.PHONY : RocketRuntime

# fast build rule for target.
RocketRuntime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/build
.PHONY : RocketRuntime/fast

#=============================================================================
# Target rules for targets named rectangle_test

# Build rule for target.
rectangle_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rectangle_test
.PHONY : rectangle_test

# fast build rule for target.
rectangle_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/build
.PHONY : rectangle_test/fast

#=============================================================================
# Target rules for targets named initializer_test

# Build rule for target.
initializer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 initializer_test
.PHONY : initializer_test

# fast build rule for target.
initializer_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/build
.PHONY : initializer_test/fast

#=============================================================================
# Target rules for targets named text_test

# Build rule for target.
text_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 text_test
.PHONY : text_test

# fast build rule for target.
text_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_test.dir/build.make CMakeFiles/text_test.dir/build
.PHONY : text_test/fast

#=============================================================================
# Target rules for targets named ui_init_test

# Build rule for target.
ui_init_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_init_test
.PHONY : ui_init_test

# fast build rule for target.
ui_init_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_init_test.dir/build.make CMakeFiles/ui_init_test.dir/build
.PHONY : ui_init_test/fast

#=============================================================================
# Target rules for targets named shader_test

# Build rule for target.
shader_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shader_test
.PHONY : shader_test

# fast build rule for target.
shader_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shader_test.dir/build.make CMakeFiles/shader_test.dir/build
.PHONY : shader_test/fast

src/astro/astroui.o: src/astro/astroui.cpp.o
.PHONY : src/astro/astroui.o

# target to build an object file
src/astro/astroui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/astro/astroui.cpp.o
.PHONY : src/astro/astroui.cpp.o

src/astro/astroui.i: src/astro/astroui.cpp.i
.PHONY : src/astro/astroui.i

# target to preprocess a source file
src/astro/astroui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/astro/astroui.cpp.i
.PHONY : src/astro/astroui.cpp.i

src/astro/astroui.s: src/astro/astroui.cpp.s
.PHONY : src/astro/astroui.s

# target to generate assembly for a file
src/astro/astroui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/astro/astroui.cpp.s
.PHONY : src/astro/astroui.cpp.s

src/rocket/asset.o: src/rocket/asset.cpp.o
.PHONY : src/rocket/asset.o

# target to build an object file
src/rocket/asset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/asset.cpp.o
.PHONY : src/rocket/asset.cpp.o

src/rocket/asset.i: src/rocket/asset.cpp.i
.PHONY : src/rocket/asset.i

# target to preprocess a source file
src/rocket/asset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/asset.cpp.i
.PHONY : src/rocket/asset.cpp.i

src/rocket/asset.s: src/rocket/asset.cpp.s
.PHONY : src/rocket/asset.s

# target to generate assembly for a file
src/rocket/asset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/asset.cpp.s
.PHONY : src/rocket/asset.cpp.s

src/rocket/font.o: src/rocket/font.cpp.o
.PHONY : src/rocket/font.o

# target to build an object file
src/rocket/font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/font.cpp.o
.PHONY : src/rocket/font.cpp.o

src/rocket/font.i: src/rocket/font.cpp.i
.PHONY : src/rocket/font.i

# target to preprocess a source file
src/rocket/font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/font.cpp.i
.PHONY : src/rocket/font.cpp.i

src/rocket/font.s: src/rocket/font.cpp.s
.PHONY : src/rocket/font.s

# target to generate assembly for a file
src/rocket/font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/font.cpp.s
.PHONY : src/rocket/font.cpp.s

src/rocket/io.o: src/rocket/io.cpp.o
.PHONY : src/rocket/io.o

# target to build an object file
src/rocket/io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/io.cpp.o
.PHONY : src/rocket/io.cpp.o

src/rocket/io.i: src/rocket/io.cpp.i
.PHONY : src/rocket/io.i

# target to preprocess a source file
src/rocket/io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/io.cpp.i
.PHONY : src/rocket/io.cpp.i

src/rocket/io.s: src/rocket/io.cpp.s
.PHONY : src/rocket/io.s

# target to generate assembly for a file
src/rocket/io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/io.cpp.s
.PHONY : src/rocket/io.cpp.s

src/rocket/renderer.o: src/rocket/renderer.cpp.o
.PHONY : src/rocket/renderer.o

# target to build an object file
src/rocket/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/renderer.cpp.o
.PHONY : src/rocket/renderer.cpp.o

src/rocket/renderer.i: src/rocket/renderer.cpp.i
.PHONY : src/rocket/renderer.i

# target to preprocess a source file
src/rocket/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/renderer.cpp.i
.PHONY : src/rocket/renderer.cpp.i

src/rocket/renderer.s: src/rocket/renderer.cpp.s
.PHONY : src/rocket/renderer.s

# target to generate assembly for a file
src/rocket/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/renderer.cpp.s
.PHONY : src/rocket/renderer.cpp.s

src/rocket/renderer3d.o: src/rocket/renderer3d.cpp.o
.PHONY : src/rocket/renderer3d.o

# target to build an object file
src/rocket/renderer3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/renderer3d.cpp.o
.PHONY : src/rocket/renderer3d.cpp.o

src/rocket/renderer3d.i: src/rocket/renderer3d.cpp.i
.PHONY : src/rocket/renderer3d.i

# target to preprocess a source file
src/rocket/renderer3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/renderer3d.cpp.i
.PHONY : src/rocket/renderer3d.cpp.i

src/rocket/renderer3d.s: src/rocket/renderer3d.cpp.s
.PHONY : src/rocket/renderer3d.s

# target to generate assembly for a file
src/rocket/renderer3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/renderer3d.cpp.s
.PHONY : src/rocket/renderer3d.cpp.s

src/rocket/runtime.o: src/rocket/runtime.cpp.o
.PHONY : src/rocket/runtime.o

# target to build an object file
src/rocket/runtime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/runtime.cpp.o
.PHONY : src/rocket/runtime.cpp.o

src/rocket/runtime.i: src/rocket/runtime.cpp.i
.PHONY : src/rocket/runtime.i

# target to preprocess a source file
src/rocket/runtime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/runtime.cpp.i
.PHONY : src/rocket/runtime.cpp.i

src/rocket/runtime.s: src/rocket/runtime.cpp.s
.PHONY : src/rocket/runtime.s

# target to generate assembly for a file
src/rocket/runtime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/runtime.cpp.s
.PHONY : src/rocket/runtime.cpp.s

src/rocket/shader.o: src/rocket/shader.cpp.o
.PHONY : src/rocket/shader.o

# target to build an object file
src/rocket/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/shader.cpp.o
.PHONY : src/rocket/shader.cpp.o

src/rocket/shader.i: src/rocket/shader.cpp.i
.PHONY : src/rocket/shader.i

# target to preprocess a source file
src/rocket/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/shader.cpp.i
.PHONY : src/rocket/shader.cpp.i

src/rocket/shader.s: src/rocket/shader.cpp.s
.PHONY : src/rocket/shader.s

# target to generate assembly for a file
src/rocket/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/shader.cpp.s
.PHONY : src/rocket/shader.cpp.s

src/rocket/text.o: src/rocket/text.cpp.o
.PHONY : src/rocket/text.o

# target to build an object file
src/rocket/text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/text.cpp.o
.PHONY : src/rocket/text.cpp.o

src/rocket/text.i: src/rocket/text.cpp.i
.PHONY : src/rocket/text.i

# target to preprocess a source file
src/rocket/text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/text.cpp.i
.PHONY : src/rocket/text.cpp.i

src/rocket/text.s: src/rocket/text.cpp.s
.PHONY : src/rocket/text.s

# target to generate assembly for a file
src/rocket/text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/text.cpp.s
.PHONY : src/rocket/text.cpp.s

src/rocket/types.o: src/rocket/types.cpp.o
.PHONY : src/rocket/types.o

# target to build an object file
src/rocket/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/types.cpp.o
.PHONY : src/rocket/types.cpp.o

src/rocket/types.i: src/rocket/types.cpp.i
.PHONY : src/rocket/types.i

# target to preprocess a source file
src/rocket/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/types.cpp.i
.PHONY : src/rocket/types.cpp.i

src/rocket/types.s: src/rocket/types.cpp.s
.PHONY : src/rocket/types.s

# target to generate assembly for a file
src/rocket/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/types.cpp.s
.PHONY : src/rocket/types.cpp.s

src/rocket/util.o: src/rocket/util.cpp.o
.PHONY : src/rocket/util.o

# target to build an object file
src/rocket/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/util.cpp.o
.PHONY : src/rocket/util.cpp.o

src/rocket/util.i: src/rocket/util.cpp.i
.PHONY : src/rocket/util.i

# target to preprocess a source file
src/rocket/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/util.cpp.i
.PHONY : src/rocket/util.cpp.i

src/rocket/util.s: src/rocket/util.cpp.s
.PHONY : src/rocket/util.s

# target to generate assembly for a file
src/rocket/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/util.cpp.s
.PHONY : src/rocket/util.cpp.s

src/rocket/window.o: src/rocket/window.cpp.o
.PHONY : src/rocket/window.o

# target to build an object file
src/rocket/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/window.cpp.o
.PHONY : src/rocket/window.cpp.o

src/rocket/window.i: src/rocket/window.cpp.i
.PHONY : src/rocket/window.i

# target to preprocess a source file
src/rocket/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/window.cpp.i
.PHONY : src/rocket/window.cpp.i

src/rocket/window.s: src/rocket/window.cpp.s
.PHONY : src/rocket/window.s

# target to generate assembly for a file
src/rocket/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RocketRuntime.dir/build.make CMakeFiles/RocketRuntime.dir/src/rocket/window.cpp.s
.PHONY : src/rocket/window.cpp.s

tests/initializer_test.o: tests/initializer_test.cpp.o
.PHONY : tests/initializer_test.o

# target to build an object file
tests/initializer_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/tests/initializer_test.cpp.o
.PHONY : tests/initializer_test.cpp.o

tests/initializer_test.i: tests/initializer_test.cpp.i
.PHONY : tests/initializer_test.i

# target to preprocess a source file
tests/initializer_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/tests/initializer_test.cpp.i
.PHONY : tests/initializer_test.cpp.i

tests/initializer_test.s: tests/initializer_test.cpp.s
.PHONY : tests/initializer_test.s

# target to generate assembly for a file
tests/initializer_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/initializer_test.dir/build.make CMakeFiles/initializer_test.dir/tests/initializer_test.cpp.s
.PHONY : tests/initializer_test.cpp.s

tests/rectangle_test.o: tests/rectangle_test.cpp.o
.PHONY : tests/rectangle_test.o

# target to build an object file
tests/rectangle_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/tests/rectangle_test.cpp.o
.PHONY : tests/rectangle_test.cpp.o

tests/rectangle_test.i: tests/rectangle_test.cpp.i
.PHONY : tests/rectangle_test.i

# target to preprocess a source file
tests/rectangle_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/tests/rectangle_test.cpp.i
.PHONY : tests/rectangle_test.cpp.i

tests/rectangle_test.s: tests/rectangle_test.cpp.s
.PHONY : tests/rectangle_test.s

# target to generate assembly for a file
tests/rectangle_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle_test.dir/build.make CMakeFiles/rectangle_test.dir/tests/rectangle_test.cpp.s
.PHONY : tests/rectangle_test.cpp.s

tests/shader_test.o: tests/shader_test.cpp.o
.PHONY : tests/shader_test.o

# target to build an object file
tests/shader_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shader_test.dir/build.make CMakeFiles/shader_test.dir/tests/shader_test.cpp.o
.PHONY : tests/shader_test.cpp.o

tests/shader_test.i: tests/shader_test.cpp.i
.PHONY : tests/shader_test.i

# target to preprocess a source file
tests/shader_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shader_test.dir/build.make CMakeFiles/shader_test.dir/tests/shader_test.cpp.i
.PHONY : tests/shader_test.cpp.i

tests/shader_test.s: tests/shader_test.cpp.s
.PHONY : tests/shader_test.s

# target to generate assembly for a file
tests/shader_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shader_test.dir/build.make CMakeFiles/shader_test.dir/tests/shader_test.cpp.s
.PHONY : tests/shader_test.cpp.s

tests/text_test.o: tests/text_test.cpp.o
.PHONY : tests/text_test.o

# target to build an object file
tests/text_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_test.dir/build.make CMakeFiles/text_test.dir/tests/text_test.cpp.o
.PHONY : tests/text_test.cpp.o

tests/text_test.i: tests/text_test.cpp.i
.PHONY : tests/text_test.i

# target to preprocess a source file
tests/text_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_test.dir/build.make CMakeFiles/text_test.dir/tests/text_test.cpp.i
.PHONY : tests/text_test.cpp.i

tests/text_test.s: tests/text_test.cpp.s
.PHONY : tests/text_test.s

# target to generate assembly for a file
tests/text_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/text_test.dir/build.make CMakeFiles/text_test.dir/tests/text_test.cpp.s
.PHONY : tests/text_test.cpp.s

tests/ui_init_test.o: tests/ui_init_test.cpp.o
.PHONY : tests/ui_init_test.o

# target to build an object file
tests/ui_init_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_init_test.dir/build.make CMakeFiles/ui_init_test.dir/tests/ui_init_test.cpp.o
.PHONY : tests/ui_init_test.cpp.o

tests/ui_init_test.i: tests/ui_init_test.cpp.i
.PHONY : tests/ui_init_test.i

# target to preprocess a source file
tests/ui_init_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_init_test.dir/build.make CMakeFiles/ui_init_test.dir/tests/ui_init_test.cpp.i
.PHONY : tests/ui_init_test.cpp.i

tests/ui_init_test.s: tests/ui_init_test.cpp.s
.PHONY : tests/ui_init_test.s

# target to generate assembly for a file
tests/ui_init_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui_init_test.dir/build.make CMakeFiles/ui_init_test.dir/tests/ui_init_test.cpp.s
.PHONY : tests/ui_init_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RocketRuntime"
	@echo "... initializer_test"
	@echo "... rectangle_test"
	@echo "... shader_test"
	@echo "... text_test"
	@echo "... ui_init_test"
	@echo "... src/astro/astroui.o"
	@echo "... src/astro/astroui.i"
	@echo "... src/astro/astroui.s"
	@echo "... src/rocket/asset.o"
	@echo "... src/rocket/asset.i"
	@echo "... src/rocket/asset.s"
	@echo "... src/rocket/font.o"
	@echo "... src/rocket/font.i"
	@echo "... src/rocket/font.s"
	@echo "... src/rocket/io.o"
	@echo "... src/rocket/io.i"
	@echo "... src/rocket/io.s"
	@echo "... src/rocket/renderer.o"
	@echo "... src/rocket/renderer.i"
	@echo "... src/rocket/renderer.s"
	@echo "... src/rocket/renderer3d.o"
	@echo "... src/rocket/renderer3d.i"
	@echo "... src/rocket/renderer3d.s"
	@echo "... src/rocket/runtime.o"
	@echo "... src/rocket/runtime.i"
	@echo "... src/rocket/runtime.s"
	@echo "... src/rocket/shader.o"
	@echo "... src/rocket/shader.i"
	@echo "... src/rocket/shader.s"
	@echo "... src/rocket/text.o"
	@echo "... src/rocket/text.i"
	@echo "... src/rocket/text.s"
	@echo "... src/rocket/types.o"
	@echo "... src/rocket/types.i"
	@echo "... src/rocket/types.s"
	@echo "... src/rocket/util.o"
	@echo "... src/rocket/util.i"
	@echo "... src/rocket/util.s"
	@echo "... src/rocket/window.o"
	@echo "... src/rocket/window.i"
	@echo "... src/rocket/window.s"
	@echo "... tests/initializer_test.o"
	@echo "... tests/initializer_test.i"
	@echo "... tests/initializer_test.s"
	@echo "... tests/rectangle_test.o"
	@echo "... tests/rectangle_test.i"
	@echo "... tests/rectangle_test.s"
	@echo "... tests/shader_test.o"
	@echo "... tests/shader_test.i"
	@echo "... tests/shader_test.s"
	@echo "... tests/text_test.o"
	@echo "... tests/text_test.i"
	@echo "... tests/text_test.s"
	@echo "... tests/ui_init_test.o"
	@echo "... tests/ui_init_test.i"
	@echo "... tests/ui_init_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

