/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn rs_rocket_log(
        log: *const ::std::os::raw::c_char,
        class_file_library_source: *const ::std::os::raw::c_char,
        function_source: *const ::std::os::raw::c_char,
        level: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn rs_rocket_exit(status_code: ::std::os::raw::c_int);
}
